### ISSUE TITLE
Does not compile under arch linux

### ISSUE THREAD

**Issue by drslwn** [joshuataylor/ddcci-driver-linux#1]
Relevant stuff:
```
==> dkms install --no-depmod ddcci/0.4.4 -k 6.8.1-arch1-1
Error! Bad return status for module build on kernel: 6.8.1-arch1-1 (x86_64)
Consult /var/lib/dkms/ddcci/0.4.4/build/make.log for more information.
```

make.log:
```
DKMS make.log for ddcci-0.4.4 for kernel 6.8.1-arch1-1 (x86_64)
Mon Mar 18 08:17:57 PM CET 2024
make: Entering directory '/var/lib/dkms/ddcci/0.4.4/build'
make -C "ddcci"
make[1]: Entering directory '/var/lib/dkms/ddcci/0.4.4/build/ddcci'
make -C "/lib/modules/6.8.1-arch1-1/build" M="/var/lib/dkms/ddcci/0.4.4/build/ddcci" modules
make[2]: Entering directory '/usr/lib/modules/6.8.1-arch1-1/build'
  CC [M]  /var/lib/dkms/ddcci/0.4.4/build/ddcci/ddcci.o
/var/lib/dkms/ddcci/0.4.4/build/ddcci/ddcci.c: In function ‘ddcci_detect’:
/var/lib/dkms/ddcci/0.4.4/build/ddcci/ddcci.c:1669:9: error: implicit declaration of function ‘strlcpy’; did you mean ‘strscpy’? [-Werror=implicit-function-declaration]
 1669 |         strlcpy(info->type, (outer_addr == DDCCI_DEFAULT_DEVICE_ADDR) ? "ddcci" : "ddcci-dependent", I2C_NAME_SIZE);
      |         ^~~~~~~
      |         strscpy
/var/lib/dkms/ddcci/0.4.4/build/ddcci/ddcci.c: At top level:
/var/lib/dkms/ddcci/0.4.4/build/ddcci/ddcci.c:1827:27: error: ‘I2C_CLASS_DDC’ undeclared here (not in a function); did you mean ‘I2C_CLASS_SPD’?
 1827 |         .class          = I2C_CLASS_DDC,
      |                           ^~~~~~~~~~~~~
      |                           I2C_CLASS_SPD
cc1: some warnings being treated as errors
make[4]: *** [scripts/Makefile.build:243: /var/lib/dkms/ddcci/0.4.4/build/ddcci/ddcci.o] Error 1
make[3]: *** [/usr/lib/modules/6.8.1-arch1-1/build/Makefile:1921: /var/lib/dkms/ddcci/0.4.4/build/ddcci] Error 2
make[2]: *** [Makefile:240: __sub-make] Error 2
make[2]: Leaving directory '/usr/lib/modules/6.8.1-arch1-1/build'
make[1]: *** [Makefile:38: ddcci.ko] Error 2
make[1]: Leaving directory '/var/lib/dkms/ddcci/0.4.4/build/ddcci'
make: *** [Makefile:28: ddcci] Error 2
make: Leaving directory '/var/lib/dkms/ddcci/0.4.4/build'
```

Changing `strlcpy` to `strscpy` and `I2C_CLASS_DDC` to `I2C_CLASS_SPD` fixed the issue and it compiles. Unfortunately, with this fix my monitor is not shown under `/sys/class/backlight` as it should according to [archlinux wiki](https://wiki.archlinux.org/title/Backlight#External_monitors).

**Comment by apteryks** [comment]
Same on Guix, when attempting to build with Linux 6.12.12.
